# -*- coding: utf-8 -*-
"""Masai Capstone Payment & Fraud Analytics Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWaff9fcGb3x2fNVce-vtARpyjNLj0aQ
"""



import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path



# BEFORE (default):
#   col1  col2  col3  ...  col20
#   1     2     3     ...  20
#
# AFTER (with these settings):
#   col1  col2  col3  col4  col5  col6  col7  ...  col20   ← All columns visible!
#   1     2     3     4     5     6     7     ...  20
# ============================================================================




pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"

print("Libraries loaded successfully!")
print(f"Pandas version: {pd.__version__}")

# =========================
# 1. Load data
# =========================


# Read the ledger, gateway file
df_ledger = pd.read_csv(DATA_DIR / "ledger.csv")
df_gateway = pd.read_csv(DATA_DIR / "gateway_export.csv")

# df_ledger = pd.read_csv("/content/ledger.csv")
#df_gateway = pd.read_csv("/content/gateway_export.csv")


# =========================
# 2. Basic inspection (No. of rows x columns)
# =========================
print("Ledger data size: ", df_ledger.shape)
print("Gateway data size: ", df_gateway.shape)


# =========================
# 3. Cleaning
# =========================

for df in [df_ledger, df_gateway]:
    df.columns = df.columns.str.strip().str.lower()
    ## end of for loop


# df_ledger["transaction_id"] = df_ledger["transaction_id"].astype(str).str.strip()
# df_gateway["transaction_id"] = df_gateway["transaction_id"].astype(str).str.strip()


## Convert date fields to datetime datatype
df_ledger["transaction_time"] = pd.to_datetime(df_ledger["transaction_time"], errors="coerce")
df_gateway["transaction_time"] = pd.to_datetime(df_gateway["transaction_time"], errors="coerce")

# =========================
# 4.To find the difference of records between ledger and gateway, use Sets
# =========================

## Create Set of ledger - unique transaction_ids, gateway - unique transaction_ids
ledgerids_set = set(df_ledger["transaction_id"])
gatewayids_set = set(df_gateway["transaction_id"])


print(f"Unique IDs (cnt) in Ledger: {len(ledgerids_set)}")
print(f"Unique IDs (cnt) in Gateway: {len(gatewayids_set)}")


# =========================
# Find ids missing in gateway, but present in ledger
# =========================
missing_ids_gateway = ledgerids_set - gatewayids_set
print(f"Missing IDs (cnt) in Gateway: {len(missing_ids_gateway)}")
##print("Missing txn_ids in Gateway: ", missing_ids_gateway)

# =========================
# Find entire rows from ids above, missing in gateway, but present in ledger
# =========================

df_missing_ids_gateway = df_ledger[df_ledger["transaction_id"].isin(missing_ids_gateway)]
##print(f"Missing df_IDs in Gateway: \n", df_missing_ids_gateway)


# =========================
# Find ids missing in ledger, but present in gateway
# =========================
missing_ids_ledger = gatewayids_set - ledgerids_set
print(f"Missing IDs (cnt) in Ledger: {len(missing_ids_ledger)}")
##print("Missing txn_ids in Ledger: ", missing_ids_ledger)


# =========================
# Find entire rows from ids above, missing in ledger, but present in gateway
# =========================

df_missing_ids_ledger = df_gateway[df_gateway["transaction_id"].isin(missing_ids_ledger)]
##print(f"Missing df_IDs in Ledger: \n", df_missing_ids_ledger)





# =========================
# 5. Join and Find Common Txn IDs
# =========================

## First join/merge ledger and gateway records (find the common records)

common_df = pd.merge(
    df_ledger,
    df_gateway,
    on="transaction_id",
    how="inner",
    indicator=True,
    suffixes=("_ledger", "_gateway")
)


print(f"There are {len(common_df)} transactions present in both systems i.e common txns...")
common_df.head()

# =========================
# 6. Find perfectly matching txns with No amount, no Status mismatches
# =========================

comparison = common_df.copy();

comparison['amount_diff'] = comparison['amount_inr_ledger'] - comparison['amount_inr_gateway']
comparison['status_match'] = comparison['status_ledger'] == comparison['status_gateway']



## Find txn records present in both, but showing Amount mismatch
amount_mismatches = comparison[comparison['amount_diff'] != 0].copy()
amount_mismatches['issue_type'] = 'AMOUNT_MISMATCH'
amount_mismatches['issue_description'] = 'Amount differs between ledger and gateway'

print(f"\nAMOUNT MISMATCHES: {len(amount_mismatches)} transactions")
print(f"Total discrepancy: ₹{amount_mismatches['amount_diff'].sum():,}")
print()
#amount_mismatches[['transaction_id', 'amount_inr_ledger', 'amount_inr_gateway', 'amount_diff']].head()
print("---Amount mismatches in common txns: ----\n", amount_mismatches[['transaction_id', 'amount_inr_ledger', 'amount_inr_gateway', 'amount_diff']])



## Find txn records present in both, but showing Status mismatch
status_mismatches = comparison[comparison['status_match'] == False].copy()
status_mismatches['issue_type'] = 'STATUS_MISMATCH'
status_mismatches['issue_description'] = 'Status differs: Ledger says SUCCESS, Gateway says FAILED'

print(f"STATUS MISMATCHES: {len(status_mismatches)} transactions")
print(f"Value affected: ₹{status_mismatches['amount_inr_ledger'].sum():,}")
print()
#status_mismatches[['transaction_id', 'amount_inr_ledger', 'amount_inr_gateway','status_ledger', 'status_gateway']].head()
print("---Status mismatches in common txns: ----\n", status_mismatches[['transaction_id', 'amount_inr_ledger', 'amount_inr_gateway','status_ledger', 'status_gateway']])

# =========================
# 7. Calculate Business Key Metrics - Headline layer:
# ========================


# Calculate Total GMV
total_gmv = df_ledger['amount_inr'].sum()

print(f"Total GMV (Ledger): ₹{total_gmv:,.2f}")

# Calculate overall success rate
status_captured_count = len(df_ledger[df_ledger["status"].str.lower() == "captured"])
total_ledger_count = len(df_ledger)
success_rate = status_captured_count / total_ledger_count * 100

print(f"Success Rate: {success_rate:.1f}%")




# Calculate Reconciliation Match Rate
# Perfectly matched records (same txn id, no amount mismatch, no status mismatch)
perfect_match_count = len(common_df) - len(amount_mismatches) - len(status_mismatches)
reconciliation_match_rate = perfect_match_count / total_ledger_count * 100
print(f"Reconciliation Match Rate: {reconciliation_match_rate:.1f}%")



# Calculate chargeback ratio - expressed as a percentage — count-based
status_chargeback_count = len(df_ledger[df_ledger["status"].str.lower() == "chargeback"])
total_ledger_count = len(df_ledger)
chargeback_ratio = status_chargeback_count / total_ledger_count * 100
print(f"Chargeback Ratio: {chargeback_ratio:.1f}%")

# =========================
## Calculating Daily Trends
# ========================


## 1. Trends layer: a time-series chart
## of daily GMV and
## daily chargeback count over the 30-day window.


## Calculate Daily GMV
daily_summary = df_ledger.copy();

daily_summary['date'] = df_ledger['transaction_time'].dt.date



daily_summary = daily_summary.groupby('date').agg({
    'transaction_id': 'count',
    'amount_inr': 'sum'
}).reset_index()
daily_summary.columns = ['date', 'transaction_count', 'total_amount']


print("----Daily Summary---\n", daily_summary)



## Get daily chargeback count
daily_chargeback = df_ledger.copy();
daily_chargeback['date'] = df_ledger['transaction_time'].dt.date
daily_chargeback = daily_chargeback[daily_chargeback['status'].str.lower() == 'chargeback'].groupby('date')['transaction_id'].count().reset_index()
daily_chargeback.columns = ['date', 'transaction_count_charegbacks']

print("----Daily Chargebcack count---\n", daily_chargeback)


# 2. Set 'date' as index and create a complete daily date range
df_indexed = daily_chargeback.set_index('date')
full_range = pd.date_range(
    start=df_indexed.index.min(), end=df_indexed.index.max(), freq='D'
)

# 3. Reindex to insert missing days filled with 0
daily_chargeback_full = (
    df_indexed.reindex(full_range, fill_value=0).reset_index()
)
daily_chargeback_full.columns = ['date', 'transaction_count_charegbacks']

print("---****-Daily Chargebcack count (full range)---\n", daily_chargeback_full)

# =========================
## Plot Charts for:
# ========================


## Plot Time-series chart for Daily GMV

plt.figure(figsize=(12, 6))
plt.plot(daily_summary['date'], daily_summary['total_amount'], marker='o', linestyle='-')
plt.title('Daily GMV Over Time')
plt.xlabel('Date')
plt.ylabel('GMV (₹)')
plt.grid(True)
plt.savefig(Path(__file__).resolve().parent / "screenshots" / "trends_layer_daily_gmv_over_time.png")

# =========================
## Trends layer: Time-series chart
# ========================

## Plot Time-series chart for Daily Chargeback count

plt.figure(figsize=(12, 5))
plt.plot(daily_chargeback_full['date'], daily_chargeback_full['transaction_count_charegbacks'],marker='o', linestyle='-')
plt.title('Daily Chargeback Count Over Time')
plt.xlabel('Date')
plt.ylabel('Chargeback Count')
plt.grid(True)
plt.savefig(Path(__file__).resolve().parent / "screenshots" / "trends_layer_daily_chargeback_count.png")

# =========================
## Build a Breakdown layer: Bar chart
# ========================


## a bar chart of GMV by payment_method
## and by category (joined from merchants).




## Bar Chart of GMV by payment method
payment_method_summary = df_ledger.groupby('payment_method')['amount_inr'].sum().reset_index()
plt.figure(figsize=(8, 5))
plt.bar(payment_method_summary['payment_method'], payment_method_summary['amount_inr'])
plt.title('GMV by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('GMV (₹)')
plt.savefig(Path(__file__).resolve().parent / "screenshots" / "breakdown_layer_gmv_by_payment_method.png")

# =========================
## Build a Breakdown layer: Bar chart
# ========================

## Build a bar chart by Merchant category (joined from merchants).

# Read the merchants file
df_merchants = pd.read_csv(DATA_DIR / "merchants.csv")



## Join df_ledger, df_merchants on merchant_id
df_ledger_merchants = pd.merge(df_ledger, df_merchants, on='merchant_id', how='left')


## Group df_ledger_merchants by category, sum by amount_inr
category_summary = df_ledger_merchants.groupby('category')['amount_inr'].sum().reset_index()
plt.figure(figsize=(10, 6))
plt.bar(category_summary['category'], category_summary['amount_inr'])
plt.title('GMV by Category')
plt.xlabel('Merchant Category')
plt.ylabel('GMV (₹)')
plt.xticks(rotation=45)
plt.savefig(Path(__file__).resolve().parent / "screenshots" / "breakdown_layer_ gmv_by_merchant_category.png")

# =========================
## Build a Details layer: Table
# ========================



## a table, rendered as a saved image (not a live/printed DataFrame),
## of the top 10 merchants by transaction count,
## with conditional highlighting (e.g., a flag column)
## for any merchant whose chargeback_ratio exceeds 1%,
## using the same count-based definition as above
## but scoped to that one merchant:
## chargeback_ratio (per-merchant) = (count of that merchant's transactions with status == "chargeback") / (count of all of that merchant's transactions).




## From df_ledger, group by merchant_id, get sum of transaction counts; order by sum of amount_inr desc
df_merchant_amount = df_ledger.groupby('merchant_id')['transaction_id'].count().reset_index()
df_merchant_amount = df_merchant_amount.sort_values(by='transaction_id', ascending=False)


#Limit top 10 records from merchant_summary
df_merchant_amount = df_merchant_amount.head(10)
df_merchant_amount.columns = ['merchant_id','merchant_txn_counts']


#From df_ledger, create a new df called df_merchant_chargeback, group by merchant_id, sum of count of txns i.e. where lower(status) = chargeback
df_merchant_chargeback = df_ledger[df_ledger['status'].str.lower() == 'chargeback'].groupby('merchant_id')['transaction_id'].count().reset_index()

df_merchant_chargeback.columns = ['merchant_id','cnt_of_chargebacks']


## Add  another column to df_merchant_chargeback called merchant_total_txn_cnt, which is group by merchant_id, sum of count of total txns
##df_merchant_chargeback['merchant_total_txn_cnt'] = df_ledger.groupby('merchant_id')['transaction_id'].count().reset_index()

# Calculate total transactions for each merchant
df_total_txns_per_merchant = df_ledger.groupby('merchant_id')['transaction_id'].count().reset_index()
df_total_txns_per_merchant.columns = ['merchant_id', 'merchant_total_txn_cnt']

# Merge this new DataFrame with df_merchant_chargeback
df_merchant_chargeback = pd.merge(df_merchant_chargeback, df_total_txns_per_merchant, on='merchant_id', how='right')



###%%%%%

#Add another column to df_merchant_chargeback called 'merchant_chargeback_ratio' = (count of transactions with lower(status) == "chargeback" for that merchant) / (count of all of that merchant's transactions)) * 100
df_merchant_chargeback['merchant_chargeback_ratio'] = (df_merchant_chargeback['cnt_of_chargebacks'] / df_merchant_chargeback["merchant_total_txn_cnt"] ) * 100

#For merchant_id = 19, print df_merchant_amount, print df_merchant_chargeback








# If merchant does not have any chargebacks in df_merchant_chargeback, then the columns: cnt_of_chargebacks, merchant_chargeback_ratio value will be 0
df_merchant_chargeback = df_merchant_chargeback.fillna(0)




## Join df_merchant_amount with df_merchant_chargeback on merchant_id, and display all records
df_merchant_summary = pd.merge(df_merchant_amount, df_merchant_chargeback, on='merchant_id', how='left')
df_merchant_summary['cnt_of_chargebacks'] = df_merchant_summary['cnt_of_chargebacks'].fillna(0)
df_merchant_summary['merchant_chargeback_ratio'] = df_merchant_summary['merchant_chargeback_ratio'].fillna(0)



## Add column 'chargeback_flag' to df_merchant_summary, which is calculated as True = if merchant_chargeback_ratio > 1%
df_merchant_summary['chargeback_flag'] = df_merchant_summary['merchant_chargeback_ratio'].apply(lambda x: True if x > 1 else False)


# Format the df_merchant_chargeback['merchant_chargeback_ratio'] column to % with 1 decimal
df_merchant_chargeback['merchant_chargeback_ratio'] = df_merchant_chargeback['merchant_chargeback_ratio'].apply(lambda x: '{:.2f}%'.format(x))




# Format df_merchant_summary['cnt_of_chargebacks'] to integer , df_merchant_summary['merchant_chargeback_ratio'] to  % with 1 decimal
df_merchant_summary['cnt_of_chargebacks'] = df_merchant_summary['cnt_of_chargebacks'].apply(lambda x: '{:.0f}'.format(x))
df_merchant_summary['merchant_chargeback_ratio'] = df_merchant_summary['merchant_chargeback_ratio'].apply(lambda x: '{:.2f}%'.format(x))







print("----Top 10 Merchant Grouped Amount---\n", df_merchant_amount)
print("----Merchant Chargeback Summary---\n", df_merchant_chargeback)
print("----Top 10 Merchant Summary---\n", df_merchant_summary)

# Function to highlight rows where 'chargeback_flag' is True
def highlight_chargeback_flag(row):
    if row['chargeback_flag']:
        return ['background-color: yellow'] * len(row)
    else:
        return [''] * len(row)

# Apply the styling to df_merchant_summary and display
display(df_merchant_summary.style.apply(highlight_chargeback_flag, axis=1))

## Add  another column to df_merchant_chargeback called merchant_total_txn_cnt, which is group by merchant_id, sum of count of total txns
#df_merchant_chargeback['merchant_total_txn_cnt'] = df_ledger.groupby('merchant_id')['transaction_id'].count().reset_index()
